name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: List web-app directory contents
        run: ls -l web_app
      - name: Build and Push Images using Docker Compose
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          MONGO_DBNAME: ${{ secrets.MONGO_DBNAME }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          FLASK_APP: ${{ secrets.FLASK_APP }}
          GITHUB_SECRET: ${{ secrets.GITHUB_SECRET }}
          GITHUB_REPO: ${{ secrets.GITHUB_REPO }}
          APP_SECRET_KEY: ${{ secrets.APP_SECRET_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
        run: |
          docker-compose build
          docker-compose push
        working-directory: ./ 